version: "3"

services:
  app:
    build: .
    restart: always
    command: "/scripts/docker/starter.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data/media:/data/media/
      # - ./data/static:/data/static/
      - ./data/log:/data/log/
      - ./requirements.txt:/requirements.txt
      - ./scripts:/scripts
    depends_on:
      - database
    env_file:
      - ./.env

  database:
    image: postgres:15.0
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
